export const GOOGLE_CITY_MAP: Record<string, string> = {
  'mumbai': 'Mumbai', 'navi mumbai': 'Mumbai', 'thane': 'Mumbai', 'dombivli': 'Mumbai',
  'kalyan': 'Mumbai', 'vasai-virar': 'Mumbai', 'virar': 'Mumbai', 'mira bhayandar': 'Mumbai',
  'bhiwandi': 'Mumbai', 'ambernath': 'Mumbai', 'nala sopara': 'Mumbai', 'palghar': 'Mumbai',
  'panvel': 'Mumbai', 'vasai': 'Mumbai', 'hyderabad': 'Hyderabad', 'secunderabad': 'Hyderabad',
  'sangareddy': 'Hyderabad', 'serilingampalli': 'Hyderabad', 'malkajgiri': 'Hyderabad',
  'balanagar': 'Hyderabad', 'patan cheruvu': 'Hyderabad', 'qutubullapur': 'Hyderabad',
  'saroornagar': 'Hyderabad', 'chennai': 'Chennai', 'shollinganallur': 'Chennai',
  'mylapore': 'Chennai', 'aminjikarai': 'Chennai', 'tambaram': 'Chennai', 'pallavaram': 'Chennai',
  'egmore': 'Chennai', 'bengaluru': 'Bengaluru', 'coimbatore': 'Coimbatore', 'pune': 'Pune',
  'pimpri-chinchwad': 'Pune', 'haveli': 'Pune', 'new delhi': 'Delhi', 'delhi': 'Delhi',
  'civil lines': 'Delhi', 'punjabi bagh': 'Delhi', 'kalkaji': 'Delhi', 'saket': 'Delhi',
  'defence colony': 'Delhi', 'saraswati vihar': 'Delhi', 'mayur vihar': 'Delhi', 'dwarka': 'Delhi',
  'rajouri garden': 'Delhi', 'preet vihar': 'Delhi', 'hauz khas': 'Delhi',
  'visakhapatnam': 'Visakhapatnam', 'ahmedabad': 'Ahmedabad', 'gandhinagar': 'Ahmedabad',
  'edappal': 'Kochi', 'ernakulam': 'Kochi', 'kochi': 'Kochi', 'kanayannur': 'Kochi',
  'noida': 'Noida', 'greater noida': 'Noida', 'dadri': 'Noida', 'gurgaon': 'Gurgaon',
  'gurugram': 'Gurgaon', 'lucknow': 'Lucknow', 'bhubaneswar': 'Bhubaneswar', 'khordha': 'Bhubaneswar',
  'karimganj': 'Bhubaneswar', 'jajapur': 'Bhubaneswar', 'jajpur': 'Bhubaneswar',
  'bargarh': 'Bhubaneswar', 'bhubaneshwar': 'Bhubaneswar', 'surat': 'Surat', 'indore': 'Indore',
  'kolkata': 'Kolkata', 'jaipur': 'Jaipur', 'vijayawada': 'Vijayawada', 'guntur': 'Guntur',
  'thiruvananthapuram': 'Thiruvananthapuram', 'guwahati': 'Guwahati', 'vadodara': 'Vadodara',
  'ludhiana': 'Ludhiana', 'rajkot': 'Rajkot', 'nashik': 'Nashik', 'ahmadabad': 'Ahmedabad',
  'faridabad': 'Faridabad', 'mangalore': 'Mangaluru', 'mangaluru': 'Mangaluru',
  'ghaziabad': 'Ghaziabad', 'warangal': 'Warangal', 'mahadevapura': 'Bengaluru',
  'jayanagar': 'Bengaluru', 'pimpri colony': 'Pune', 'howrah': 'Kolkata', 'nigdi': 'Pune',
  'vashi': 'Mumbai', 'ghansoli': 'Mumbai', 'sanpada': 'Mumbai', 'chinchwad': 'Pune',
  'ravet': 'Pune', 'kanchipuram': 'Chennai', 'thiruvallur': 'Chennai', 'mahape': 'Mumbai',
  'brookefield': 'Bengaluru', 'krishnarajapura': 'Bengaluru', 'malad east': 'Mumbai',
  'wakad': 'Pune', 'kandivali east': 'Mumbai', 'c v raman nagar': 'Bengaluru',
  'nizampet': 'Hyderabad', 'velachery': 'Chennai', 'mira road east': 'Mumbai',
  'koramangala': 'Bengaluru', 'balagere': 'Bengaluru', 'indirapuram': 'Bengaluru',
  'seawoods': 'Mumbai', 'jubilee hills': 'Hyderabad', 'worli': 'Mumbai', 'ulhasnagar': 'Mumbai',
  'tharamani': 'Chennai', 'rajajinagar': 'Bengaluru', 'alwal': 'Hyderabad',
  'amrapali leisure valley': 'Noida', 'wagholi': 'Pune', 'pimple nilakh': 'Pune',
  'mulund west': 'Mumbai', 'bhandup west': 'Mumbai', 'madipakkam': 'Chennai',
  'medavakkam': 'Chennai', 'vasant vihar': 'Delhi', 'kondhwa': 'Pune', 'banjara hills': 'Hyderabad',
  'sholinganallur': 'Chennai', 'mundhwa': 'Pune', 'bellandur': 'Bengaluru', 'tangra': 'Kolkata',
  'manapakkam': 'Chennai', 'virar east': 'Mumbai', 'vasant kunj': 'Delhi', 'sector 62': 'Noida',
  'nayanda halli': 'Bengaluru', 'rayasandra': 'Bengaluru', 'lajpat nagar': 'Delhi',
  'fort': 'Mumbai', 'viman nagar': 'Pune', 'khairtabad': 'Hyderabad', 'greater kailash': 'Delhi',
  'jogeshwari east': 'Mumbai', 'bhayandar east': 'Mumbai', 'cbd belapur': 'Mumbai',
  'panaji': 'Goa', 'mysuru': 'Mysore', 'sahibzada ajit singh nagar': 'Mohali',
  'chandigarh': 'Chandigarh', 'krishnarajapuram': 'Bengaluru', 'rabale': 'Mumbai',
  'cherlapalli': 'Hyderabad', 'badarpur': 'Delhi', 'mazgaon': 'Mumbai', 'george town': 'Chennai',
  'ashok vihar': 'Delhi', 'nagpur': 'Nagpur', 'old goa': 'Goa', 'indiranagar': 'Bengaluru',
  'bachupally': 'Hyderabad', 'subramanyapura': 'Bengaluru', 'meenambakkam': 'Chennai',
  'manchirevula': 'Hyderabad', 'bolarum': 'Hyderabad', 'sector 18': 'Noida',
  'rama krishna puram': 'Delhi', 'narayanapura': 'Bengaluru', 'thrissur': 'Thrissur',
  'bandra west': 'Mumbai', 'byculla': 'Mumbai', 'juhu': 'Mumbai', 'dahisar west': 'Mumbai',
  'parel': 'Mumbai', 'sector 54': 'Gurgaon', 'amrapali dream valley': 'Noida',
  'wadgaon sheri': 'Pune', 'khadakpada': 'Mumbai', 'mukherjee nagar': 'Delhi',
  'bodakdev': 'Ahmedabad', 'yerawada': 'Pune', 'dhanori': 'Pune', 'mehrauli': 'Delhi',
  'athwa': 'Surat', 'sector 62a': 'Noida', 'bopal': 'Ahmedabad', 'kudlu': 'Bengaluru',
  'saravanampatti': 'Coimbatore', 'madambakkam': 'Chennai', 'pratap vihar': 'Ghaziabad',
  'nungambakkam': 'Chennai', 'malviya nagar': 'Delhi', 'bhakti nagar': 'Rajkot',
  'shalimar bagh': 'Delhi', 'akurdi': 'Pune', 'nayapalli': 'Bhubaneswar', 'paldi': 'Ahmedabad',
  'pammal': 'Chennai', 'kodungaiyur': 'Chennai', 'kovilambakkam': 'Chennai', 'elamakkara': 'Kochi',
  'thiruverkadu': 'Chennai', 'injambakkam': 'Chennai', 'yamuna bank': 'Delhi',
  'maninagar': 'Ahmedabad', 'akshayanagar': 'Bengaluru', 'jagathgiri gutta': 'Hyderabad',
  'shankar vihar': 'Delhi', 'dilshad garden': 'Delhi', 'chikkakannalli': 'Bengaluru',
  'korattur': 'Chennai', 'hastinapuram': 'Hyderabad', 'nikol': 'Ahmedabad', 'ghorpadi': 'Pune',
  'wanowrie': 'Pune', 'patna': 'Patna', 'dehradun': 'Dehradun',
  'nizamabad, telangana': 'Hyderabad', 'hubballi': 'Hubballi', 'salem': 'Salem',
  'chhatrapati sambhajinagar': 'Sambhaji Nagar', 'aurangabad': 'Sambhaji Nagar',
  'belgaum': 'Belgaum', 'belagavi': 'Belgaum', 'kakinada': 'Kakinada', 'bhopal': 'Bhopal',
  'kolhapur': 'Kolhapur', 'kozhikode': 'Kozhikode', 'madurai': 'Madurai', 'kanpur': 'Kanpur',
  'sambhaji nagar': 'Sambhaji Nagar', 'tiruchirappalli': 'Tiruchirappalli', 'kota': 'Kota',
  'tiruppur': 'Tiruppur', 'tirupati': 'Tirupati', 'rajahmundry': 'Rajahmundry',
  'rajamahendravaram': 'Rajahmundry', 'udaipur': 'Udaipur', 'sangli miraj kupwad': 'Sangli',
  'sangli': 'Sangli', 'karimnagar': 'KarimNagar', 'bellari': 'Ballari', 'ballari': 'Ballari',
  'hosur': 'Hosur', 'atal nagar-nava raipur': 'Raipur', 'raipur': 'Raipur', 'nanded': 'Nanded',
  'nanded-waghala': 'Nanded', 'puducherry': 'Puducherry',
};

export const TSC_CITIES = [
  'Mumbai', 'Hyderabad', 'Chennai', 'Bengaluru', 'Coimbatore', 'Pune', 'Delhi', 
  'Visakhapatnam', 'Ahmedabad', 'Kochi', 'Noida', 'Gurgaon', 'Lucknow', 'Bhubaneswar', 
  'Surat', 'Indore', 'Kolkata', 'Jaipur', 'Vijayawada', 'Guntur', 'Thiruvananthapuram', 
  'Guwahati', 'Vadodara', 'Ludhiana', 'Rajkot', 'Nashik', 'Faridabad', 'Mangaluru', 
  'Ghaziabad', 'Warangal', 'Goa', 'Mysore', 'Mohali', 'Chandigarh', 'Nagpur', 'Thrissur', 
  'Patna', 'Dehradun', 'Hubballi', 'Salem', 'Sambhaji Nagar', 'Belgaum', 'Kakinada', 
  'Bhopal', 'Kolhapur', 'Kozhikode', 'Madurai', 'Kanpur', 'Tiruchirappalli', 'Kota', 
  'Tiruppur', 'Tirupati', 'Rajahmundry', 'Udaipur', 'Sangli', 'KarimNagar', 'Ballari', 
  'Hosur', 'Raipur', 'Nanded', 'Puducherry', 'Rest', 'Unknown'
];

export function mapGoogleCity(googleCityName: string): string {
  if (!googleCityName || googleCityName.trim() === '') return 'Unknown';
  const lower = googleCityName.toLowerCase().trim();
  return GOOGLE_CITY_MAP[lower] || 'Rest';
}
